spring:
  profiles:
    active: dev
---

server:
  port: 8002
spring:
  application:
    name: provider-web-8002
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles: dev
eureka:
  instance:
    instance-id: provider-web-8002 # 服务名
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7004.com:7004/eureka/
      
---

server:
  port: 8003
spring:
  application:
    name: provider-web-8003
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles: test
eureka:
  instance:
    instance-id: provider-web-8003 # 服务名
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7004.com:7004/eureka/
